name: Build and install docassemble

on: push

jobs:
  build-n-check:
    runs-on: ubuntu-latest
    name: Building docassemble package
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.13"
        - name: Install pypa/build
          run: python -m pip install build dayamlchecker --user

        - name: Check syntax for all files
          run: python -m compileall . -q

        - name: Build a binary wheel and a source tarball
          run: python -m build --sdist --wheel --outdir dist/

        - name: Run YAML Checker
          run: python -m dayamlchecker $(find . -name "*.yml" -path "*/questions/*")